# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22e4f657884b07f5953c8f8f33b5a8d90bd26f010a37e4cb293ac4d3a2d68d16a512632d53b9a42cca26bca6ae2aef8c59a2df289ba6ece3775800dcac9528cd

test:
  secret_key_base: f8f4ef47c33611f9f3fa90c16821b65e02813de9f40e4fe49346fd21c9b591509cea990eaf312b056b811fd0c4b0001a8ae30e9d2df925eccd6a499cde61df7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
